Project4/Models/Showing.cs
namespace Project4.Models
{
    //Showing Status
    public enum ShowingStatus
    {
        Pending,
        Rejected,
        Accepted
    }
    public class Showing : ICloneable<Showing>
    {
        //Fields
        private int? showingID;
        private int homeID;
        private Client client;
        private DateTime timeRequestCreated;
        private DateTime showingTime;
        private ShowingStatus status;

        public Showing(int homeID, Client client, DateTime timeRequestCreated, DateTime showingTime, ShowingStatus status)
        {
            showingID = null;
            this.homeID = homeID;
            this.client = client.Clone();
            this.timeRequestCreated = new DateTime(timeRequestCreated.Ticks);
            this.showingTime = new DateTime(showingTime.Ticks);
            this.status = status;
        }

        public Showing(int? showingID, int homeID, Client client, DateTime timeRequestCreated, DateTime showingTime, ShowingStatus status)
        {
            this.showingID = showingID;
            this.homeID = homeID;
            this.client = client.Clone();
            this.timeRequestCreated = new DateTime(timeRequestCreated.Ticks);
            this.showingTime = new DateTime(showingTime.Ticks);
            this.status = status;
        }

        public int? ShowingID
        {
            get { return showingID; }
            set { showingID = value; }
        }
        public int HomeID
        {
            get { return homeID; }
            set { homeID = value; }
        }
        public Client Client
        {
            get { return client.Clone(); }
            set { client = value.Clone(); }
        }
        public DateTime TimeRequestCreated
        {
            get { return new DateTime(timeRequestCreated.Ticks); }
            set { timeRequestCreated = new DateTime(value.Ticks); }
        }
        public DateTime ShowingTime
        {
            get { return new DateTime(showingTime.Ticks); }
            set { showingTime = new DateTime(value.Ticks); }
        }
        public ShowingStatus Status
        {
            get { return status; }
            set { status = value; }
        }

        public Showing Clone()
        {
            return new Showing(ShowingID, HomeID, Client, TimeRequestCreated, ShowingTime, Status);
        }
    }
}

Project4/Models/Showings.cs
namespace Project4.Models
{
    public class Showings : ListOfObjects<Showing>, ICloneable<Showings>
    {
        public Showings() { }
        public Showings(List<Showing> list) { List = list; }
        public Showings Clone()
        {
            return new Showings(List);
        }
    }
}

Project4/Models/ViewModels/ScheduleShowingViewModel.cs
namespace Project4.Models.ViewModels
{
    public class ScheduleShowingViewModel
    {
        public Home? home { get; set; }
    }
}

Project4/Controllers/ShowingController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Project4.Models;
using Project4.Models.ViewModels;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Project4.Controllers
{
    //Handles Showing Create and Manage
    public class ShowingController : Controller
    {
        [HttpPost]
        public IActionResult ViewShowings()
        {
            if (HttpContext.Session.GetString("Agent") != null)
            {
                string agentJson = HttpContext.Session.GetString("Agent");
                Agent agent = System.Text.Json.JsonSerializer.Deserialize<Agent>(agentJson);
                try
                {
                    Showings showings = ReadShowing.GetShowingsByAgentID(agent.AgentID);
                    TempData["Showings"] = showings;
                    return View();
                } catch (Exception ex)
                {
                    //Send to Error Page
                    return ViewShowingErrorConfirm(false, new List<string>
                    {
                        $"Error Message: {ex}"
                    });
                }
            }
            //Send to Error Page
            return ViewShowingErrorConfirm(false, new List<string>
            {
                $"You are not signed in as an Agent"
            });
        }

        [HttpPost]
        public IActionResult ChangeStatus()
        {
            try
            {
                if (HttpContext.Session.GetString("Agent") == null) 
                {
                    //Send to Error Page
                    return ViewShowingErrorConfirm(false, new List<string>
                    {
                        $"You are not signed in as an Agent"
                    });
                }
                int showingID = int.Parse(Request.Form["ShowingID"].ToString());
                ShowingStatus showingStatus = (ShowingStatus)Enum.Parse(typeof(ShowingStatus), Request.Form["ddlShowingStatus"].ToString());
                ShowingStatus originalShowingStatus = (ShowingStatus)Enum.Parse(typeof(ShowingStatus), TempData["OriginalShowingStatus"].ToString());
                if(showingStatus == originalShowingStatus)
                {
                    //Send to Error Page
                    return ViewShowingErrorConfirm(false, new List<string>
                    {
                        $"ShowingID: {showingID} is already Status: {showingStatus}"
                    });
                }
                else if(WriteShowing.UpdateStatus(showingID, showingStatus))
                {
                    return ViewShowingErrorConfirm(true, new List<string>
                    {
                        $"ShowingID: {showingID} status updated to Status: {showingStatus.ToString()}"
                    });
                }
                else
                {
                    return ViewShowingErrorConfirm(false, new List<string>
                    {
                        $"{showingID} status NOT updated"
                    });
                }
            }
            catch (Exception ex)
            {
                //Send to Error Page
                return ViewShowingErrorConfirm(false, new List<string>
                {
                    $"Error Message: {ex}"
                });
            }
        }

        public IActionResult ScheduleShowing()
        {
            TempData.Clear();
            try
            {
                string homeJson = HttpContext.Session.GetString("ShowingHome");
                Home showingHome = JsonConvert.DeserializeObject<Home>(homeJson);
                TempData["Home"] = showingHome;
                return View();

            } catch (Exception ex)
            {
                //Send to Error Page
                return MakeShowingErrorConfirm(false, new List<string>
                {
                    $"Error Message: {ex}"
                });
            }
        }

        [HttpPost]
        public IActionResult ShowingRequest()
        {
            if (!ValidateMakeShowing()) 
            {
                Home showingHome = JsonConvert.DeserializeObject<Home>(HttpContext.Session.GetString("ShowingHome"));
                TempData["Home"] = showingHome;
                return View("ScheduleShowing"); 
            }
            string homeJson = HttpContext.Session.GetString("ShowingHome");
            Home home = JsonConvert.DeserializeObject<Home>(homeJson);
            string firstName = Request.Form["txtFirstName"];
            string lastName = Request.Form["txtLastName"];
            string street = Request.Form["txtStreet"];
            string city = Request.Form["txtCity"];
            States state = (States)Enum.Parse(typeof(States), Request.Form["ddlState"].ToString());
            string zipCode = Request.Form["txtZipCode"];
            string phoneNumber = Request.Form["txtPhoneNumber"];
            string email = Request.Form["txtEmail"];
            Client client = new Client(
                    firstName,
                    lastName,
                    new Address(street, city, state, zipCode),
                    phoneNumber,
                    email
                );
            DateTime showingTime = DateTime.Parse(Request.Form["dateShowingTime"]);
            Showing showing = new Showing(
                (int)home.HomeID,
                client,
                DateTime.Now,
                showingTime,
                ShowingStatus.Pending
                );

            try
            {
                if(WriteShowing.CreateNew(showing))
                {
                    return MakeShowingErrorConfirm(true, new List<string>
                    {
                        $"Congratulations {showing.Client.FirstName} {showing.Client.LastName}!",
                        $"You made a showing request for {showing.ShowingTime}"
                    });
                }
                else
                {
                    return MakeShowingErrorConfirm(false, new List<string>
                    {
                        $"Sorry {showing.Client.FirstName} {showing.Client.LastName}.",
                        $"failed to make a showing request"
                    });
                }
            }
            catch (Exception ex)
            {
                return MakeShowingErrorConfirm(false, new List<string>
                {
                    $"Error Message: {ex}"
                });
            }
        }
        //Validate Make Showing inputs
        public bool ValidateMakeShowing()
        {
            RetainData();
            List<string> errors = new List<string>();
            // Validate Fields
            if (string.IsNullOrEmpty(Request.Form["txtFirstName"]) || !Regex.IsMatch(Request.Form["txtFirstName"], @"\S+"))
            {
                errors.Add("First Name is invalid or cannot be null.");
            }
            if (string.IsNullOrEmpty(Request.Form["txtLastName"]) || !Regex.IsMatch(Request.Form["txtLastName"], @"\S+"))
            {
                errors.Add("Last Name is invalid or cannot be null.");
            }
            if (string.IsNullOrEmpty(Request.Form["txtStreet"]) || !Regex.IsMatch(Request.Form["txtStreet"], @"\S+"))
            {
                errors.Add("Street is invalid or cannot be null.");
            }
            if (string.IsNullOrEmpty(Request.Form["ddlState"]) || !Regex.IsMatch(Request.Form["ddlState"], @"\S+"))
            {
                errors.Add("State is invalid or cannot be null.");
            }
            if (string.IsNullOrEmpty(Request.Form["txtZipCode"]) || !Regex.IsMatch(Request.Form["txtZipCode"], @"^\d{5}(-\d{4})?$"))
            {
                errors.Add("Zip Code is invalid. It must be 5 digits or in ZIP+4 format.");
            }
            if (string.IsNullOrEmpty(Request.Form["txtPhoneNumber"]) || !Regex.IsMatch(Request.Form["txtPhoneNumber"], @"^\d{9,10}$"))
            {
                errors.Add("Phone Number is invalid. It must be 9 or 10 digits.");
            }
            if (string.IsNullOrEmpty(Request.Form["txtEmail"]) || !Regex.IsMatch(Request.Form["txtEmail"], @"^[^@\s]+@temple\.edu$"))
            {
                errors.Add("Email is invalid. It must be a Temple University email address.");
            }
            if (string.IsNullOrEmpty(Request.Form["dateShowingTime"]) || !DateTime.TryParse(Request.Form["dateShowingTime"], out DateTime showingTime) || showingTime < DateTime.Now)
            {
                errors.Add("Showing Time is invalid, cannot be null, and must be a future date.");
            }


            if (errors.Count > 0 )
            {
                TempData["Errors"] = errors;
                return false;
            }
            return true;
        }
        //save request.form to temp data
        public void RetainData()
        {
            foreach (string key in Request.Form.Keys)
            {
                TempData[key] = Request.Form[key];
            }
            TempData.Keep();
        }

        //Sends user to confirmation or error page
        public IActionResult ViewShowingErrorConfirm(bool confirm, List<string> message)
        {
            //Send to Error Page
            TempData["Message"] = JsonConvert.SerializeObject(message);
            TempData["Action"] = "AgentDashboard";
            TempData["Controller"] = "Account";
            if (confirm)
            {
                return RedirectToAction("SharedConfirmation", "Shared");
            }
            return RedirectToAction("SharedError", "Shared");
        }
        public IActionResult MakeShowingErrorConfirm(bool confirm, List<string> message)
        {
            //Send to Error Page
            TempData["Message"] = JsonConvert.SerializeObject(message);
            TempData["Action"] = "Dashboard";
            TempData["Controller"] = "Dashboard";
            if (confirm)
            {

Project4/Views/Showing/ScheduleShowing.cshtml
@{
    ViewData["Title"] = "Project 4 - Schedule Showing";
    Home home = (Home)TempData["Home"];
    List<string> errors = null;
    if (TempData["Errors"] != null)
    {
        errors = (List<string>)TempData["Errors"];
    }
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8" />
</head>
<body>
    <div class="container my-4">
        @if (TempData["Home"] != null)
        {
            <form asp-controller="Showing" asp-action="ShowingRequest" method="POST" class="card shadow mt-5 p-4">
                <h4 class="card-title mb-4">Schedule Showing</h4>
                <h5 class="mb-3">Home Information</h5>
                <div class="row g-3">
                    <div class="col-md-6">
                        <p class="mb-0"><strong>Home Address:</strong> @home.Address.ToString()</p>
                    </div>
                    <div class="col-md-6">
                        <p class="mb-0"><strong>Home Property Type:</strong> @home.PropertyType</p>
                    </div>
                    <div class="col-md-6">
                        <p class="mb-0"><strong>Home Cost:</strong> @home.Cost</p>
                    </div>
                    <div class="col-md-6">
                        <p class="mb-0"><strong>Home Date Listed:</strong> @home.DateListed</p>
                    </div>
                    <div class="col-md-6">
                        <p class="mb-0"><strong>Agent ID Assigned to Home:</strong> @home.AgentID</p>
                    </div>
                    <div class="col-md-6">
                        <p class="mb-0"><strong>Home Year Constructed:</strong> @home.YearConstructed</p>
                    </div>
                </div>
                <h5 class="mb-3">Client Information</h5>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="txtFirstName" class="form-label">First Name</label>
                        <input id="txtFirstName" name="txtFirstName" class="form-control" value="@TempData["txtFirstName"]" />
                    </div>
                    <div class="col-md-6">
                        <label for="txtLastName" class="form-label">Last Name</label>
                        <input id="txtLastName" name="txtLastName" class="form-control" value="@TempData["txtLastName"]" />
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="txtStreet" class="form-label">Street</label>
                        <input id="txtStreet" name="txtStreet" class="form-control" value="@TempData["txtStreet"]" />
                    </div>
                    <div class="col-md-6">
                        <label for="txtCity" class="form-label">City</label>
                        <input id="txtCity" name="txtCity" class="form-control" value="@TempData["txtCity"]" />
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="ddlState" class="form-label">State</label>
                        <select id="ddlState" name="ddlState" class="form-control">
                            @foreach (States state in Enum.GetValues(typeof(States)))
                            {
                                @if (TempData["ddlState"] != null && TempData["ddlState"].ToString() == state.ToString())
                                {
                                    <option value="@state" selected>@state</option>
                                }
                                else
                                {
                                    <option value="@state">@state</option>
                                }
                            }
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label for="txtZipCode" class="form-label">Zip Code</label>
                        <input id="txtZipCode" name="txtZipCode" class="form-control" value="@TempData["txtZipCode"]" />
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="txtPhoneNumber" class="form-label">Phone Number</label>
                        <input id="txtPhoneNumber" name="txtPhoneNumber" class="form-control" value="@TempData["txtPhoneNumber"]" />
                    </div>
                    <div class="col-md-6">
                        <label for="txtEmail" class="form-label">Email</label>
                        <input id="txtEmail" name="txtEmail" class="form-control" value="@TempData["txtEmail"]" />
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="dateShowingTime" class="form-label">Showing Time</label>
                        <input id="dateShowingTime" name="dateShowingTime" type="date" class="form-control" value="@TempData["dateShowingTime"]" />
                    </div>
                </div>
                <div class="d-flex justify-content-between mt-4">
                    <button id="btnSubmitShowing" type="submit" class="btn btn-success w-100">Schedule</button>
                </div>
                @if (errors != null)
                {
                    <div class="mt-3">
                        @foreach (string error in errors)
                        {
                            <p class="text-danger">@error</p>
                        }
                    </div>
                }
            </form>
        }
        else
        {
            <h1 class="text-center text-warning mt-5">No Home Provided...</h1>
        }
    </div>
</body>
</html>

Project4/Views/Showing/ViewShowings.cshtml
@{
    ViewData["Title"] = "Project 4 - View Showing";
    Layout = "~/Views/Shared/_AgentLayout.cshtml";
    Showings showings = (Showings)TempData["Showings"];
}

<!DOCTYPE html>
<html>
    <head>
        <title>@ViewData["Title"]</title>
        <meta charset="utf-8" />
    </head>
    <body>
<div class="container">
    <div class="row p-4 shadow mt-5 mb-5">
        <h1>Showings</h1>
        @if(showings != null && showings.List.Count > 0)
        {
            @foreach (Showing showing in @showings.List)
            {
            if(showing.Status == ShowingStatus.Pending)
            {
            <div class="col-md-4 mt-4 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                <form asp-controller="Showing" asp-action="ChangeStatus" method="POST">
                    <div>
                        <input type="hidden" name="ShowingID" value="@showing.ShowingID"/>
                        <h2>Showing ID: @showing.ShowingID</h2>
                        <span>Home: @showing.HomeID</span><br />
                        <span>Client Name: @showing.Client.FirstName @showing.Client.LastName</span><br />
                        <span>Showing Time: @showing.ShowingTime.ToShortDateString()</span><br />
                        <span>Time Requested: @showing.TimeRequestCreated.ToLongDateString()</span><br />
                        <span>Status:</span>
                        <select name="ddlShowingStatus" id="showingStatus">
                            @foreach (ShowingStatus status in Enum.GetValues(typeof(ShowingStatus)))
                            {
                                if(showing.Status == status)
                                {
                                    <option value="@status" selected="selected">@status</option>
                                    @(TempData["OriginalShowingStatus"] = @status);
                                } else
                                {
                                    <option value="@status">@status</option>
                                }
                            }
                        </select>
                        <button class="btn btn-primary btn-sm me-2" type="submit" name="btnChangeStatus">Change Status</button>
                    </div>
                </form>
        </div>
        </div>
        </div>
            }
            }
        }
        else if(showings.List.Count == 0) {
            <p>This Agent has no showing requests</p>
        }
        else
        {
            <p>No showings...</p>
        }
        </div>
        </div>
</body>
</html>