Project4/Models/Offer.cs
namespace Project4.Models
{
    public enum OfferStatus
    {
        Pending,
        Rejected,
        Accepted
    }

    public enum TypeOfSale
    {
        Cash,
        ConventionalMortgage
    }
    public class Offer : ICloneable<Offer>
    {
        private int offerID;
        private Home home;
        private Client client;
        private int amount;
        private TypeOfSale typeOfSale;
        private bool sellHomePrior;
        private DateTime moveInDate;
        private OfferStatus status;

        public int OfferID
        {
            get { return offerID; }
            set { offerID = value; }
        }

        public Home Home
        {
            get { return home; }
            set { home = value; }
        }

        public Client Client
        {
            get { return client; }
            set { client = value; }
        }

        public int Amount
        {
            get { return amount; }
            set { amount = value; }
        }

        public TypeOfSale TypeOfSale
        {
            get { return typeOfSale; }
            set { typeOfSale = value; }
        }

        public bool SellHomePrior
        {
            get { return sellHomePrior; }
            set { sellHomePrior = value; }
        }

        public DateTime MoveInDate
        {
            get { return moveInDate; }
            set { moveInDate = value; }
        }

        public OfferStatus Status
        {
            get { return status; }
            set { status = value; }
        }

        public Offer(int id, Home home, Client client, int offerAmount, TypeOfSale saleType, bool sellHome, DateTime moveInDate, OfferStatus status)
        {
            OfferID = id;
            Home = home;
            Client = client;
            Amount = offerAmount;
            TypeOfSale = saleType;
            SellHomePrior = sellHome;
            MoveInDate = moveInDate;
            Status = status;
        }

        public Offer(Home home, Client client, int offerAmount, TypeOfSale saleType, bool sellHome, DateTime moveInDate, OfferStatus status)
        {
            Home = home;
            Client = client;
            Amount = offerAmount;
            TypeOfSale = saleType;
            SellHomePrior = sellHome;
            MoveInDate = moveInDate;
            Status = status;
        }

        public Offer Clone()
        {
            return new Offer(OfferID, Home, Client, Amount, TypeOfSale, SellHomePrior, MoveInDate, Status);
        }
    }
}

Project4/Models/Offers.cs
namespace Project4.Models
{
    public class Offers : ListOfObjects<Offer>
    {
        public Offers() { }

        public Offers(List<Offer> list) { List = list; }

        public Offers Clone()
        {
            return new Offers(List);
        }
    }
}

Project4/Models/ViewModels/MakeOfferViewModel.cs
namespace Project4.Models.ViewModels
{
    public class MakeOfferViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string SaleType { get; set; }

        public string OfferAmount { get; set; }

        public string NewContingency { get; set; }

        public bool SellCurrentHome { get; set; }

        public DateTime MoveInDate { get; set; }

        public Contingencies offerContingencies;
    }
}

Project4/Models/ViewModels/ViewOffersViewModel.cs
namespace Project4.Models.ViewModels
{
    public class ViewOffersViewModel
    {
        public Offers allOffers { get; set; }
    }
}

Project4/Controllers/OfferController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Project4.Models;
using Project4.Models.ViewModels;
using System.Net;
using System.Reflection;
using System.Text;

namespace Project4.Controllers
{
	//Handles Offer Create and Manage
	public class OfferController : Controller
	{
		[HttpPost]

		public IActionResult MakeOffer(int homeID)
		{
			if (homeID > 0)
			{
				string apiUrl = $"https://cis-iis2.temple.edu/Fall2024/CIS3342_tui78495/WebAPI/ReadHome/ReadSingleHomeListing/{homeID}";
				WebRequest request = WebRequest.Create(apiUrl);
				WebResponse resposne = request.GetResponse();
				Stream dataStream = resposne.GetResponseStream();
				StreamReader reader = new StreamReader(dataStream);
				string data = reader.ReadToEnd();
				reader.Close();
				resposne.Close();
				Home currentHome = JsonConvert.DeserializeObject<Home>(data);
				string seralizedHome = JsonConvert.SerializeObject(currentHome);
				HttpContext.Session.SetString("CurrentHome", seralizedHome);
				if (HttpContext.Session.GetString("OfferContingencies") == null)
				{
					List<string> currentContingencies = new List<string>();
					string seralizedContingencies = JsonConvert.SerializeObject(currentContingencies);
					HttpContext.Session.SetString("OfferContingencies", seralizedContingencies);
					ViewBag.OfferContingencies = currentContingencies;
					return View();
				}
				else
				{
					string seralizedContingencies = HttpContext.Session.GetString("OfferContingencies");
					List<string> currentContingencies = JsonConvert.DeserializeObject<List<string>>(seralizedContingencies);
					ViewBag.OfferContingencies = currentContingencies;
					return View();
				}
			}
			else
			{
				return RedirectToAction("Dashboard", "Dashboard");
			}

		}
		[HttpPost]
		public IActionResult AddContingency(string newContingency)
		{
			ViewBag.FirstName = Request.Form["FirstName"];
			ViewBag.LastName = Request.Form["LastName"];
			ViewBag.Email = Request.Form["Email"];
			ViewBag.Phone = Request.Form["Phone"];
			ViewBag.ClientAddress = Request.Form["clientAddress"];
			ViewBag.ClientCity = Request.Form["clientCity"];
			ViewBag.ClientZip = Request.Form["clientZip"];
			ViewBag.OfferAmount = Request.Form["OfferAmount"];
			ViewBag.MoveInDate = Request.Form["MoveInDate"];
			if (newContingency == "")
			{
				ViewBag.OfferError = "Contingency cannot be empty.";
			}
			else
			{
				string seralizedContingencies = HttpContext.Session.GetString("OfferContingencies");
				List<string> currentContingencies = JsonConvert.DeserializeObject<List<string>>(seralizedContingencies);
				currentContingencies.Add(newContingency);
				seralizedContingencies = JsonConvert.SerializeObject(currentContingencies);
				HttpContext.Session.SetString("OfferContingencies", seralizedContingencies);
				ViewBag.OfferContingencies = currentContingencies;
			}
			return View("MakeOffer");

		}
		[HttpPost]
		public IActionResult RemoveContingency(string removedContingency)
		{
			ViewBag.FirstName = Request.Form["FirstName"];
			ViewBag.LastName = Request.Form["LastName"];
			ViewBag.Email = Request.Form["Email"];
			ViewBag.Phone = Request.Form["Phone"];
			ViewBag.ClientAddress = Request.Form["clientAddress"];
			ViewBag.ClientCity = Request.Form["clientCity"];
			ViewBag.ClientZip = Request.Form["clientZip"];
			ViewBag.OfferAmount = Request.Form["OfferAmount"];
			ViewBag.MoveInDate = Request.Form["MoveInDate"];
			string seralizedContingencies = HttpContext.Session.GetString("OfferContingencies");
			List<string> currentContingencies = JsonConvert.DeserializeObject<List<string>>(seralizedContingencies);

			if (currentContingencies.Contains(removedContingency))
			{
				currentContingencies.Remove(removedContingency);
			}
			seralizedContingencies = JsonConvert.SerializeObject(currentContingencies);
			HttpContext.Session.SetString("OfferContingencies", seralizedContingencies);
			ViewBag.OfferContingencies = currentContingencies;

			return View("MakeOffer");
		}

		public IActionResult AllOffers()
		{
			if (HttpContext.Session.GetString("Agent") == null) { return RedirectToAction("Dashboard", "Dashboard"); }
			string agentSession = HttpContext.Session.GetString("Agent");
			Agent currentAgent = JsonConvert.DeserializeObject<Agent>(agentSession);
			ViewBag.Agent = currentAgent;
			return View("AllOffers");
		}


		public IActionResult FinalizeOffer()
		{
			string firstName = Request.Form["FirstName"];
			string lastName = Request.Form["LastName"];
			string email = Request.Form["Email"];
			string phone = Request.Form["Phone"];
			string offerAmount = Request.Form["OfferAmount"];
			string saleType = Request.Form["SaleType"];
			string sellHome = Request.Form["SellHomePrior"];
			string moveInDate = Request.Form["MoveInDate"];
			string clientAddress = Request.Form["clientAddress"];
			string clientCity = Request.Form["clientCity"];
			string clientState = Request.Form["clientState"];
			string clientZip = Request.Form["clientZip"];
			List<string> inputs = new List<string>();
			inputs.Add(firstName);
			inputs.Add(lastName);
			inputs.Add(email);
			inputs.Add(phone);
			inputs.Add(offerAmount);
			inputs.Add(sellHome);
			inputs.Add(moveInDate);
			inputs.Add(clientAddress);
			inputs.Add(clientCity);
			inputs.Add(clientZip);

			if (ValidateOffer(inputs) == false)
			{
				ViewBag.OfferError = "Please fix errors below and resubmit the offer!";
				ViewBag.FirstName = firstName;
				ViewBag.LastName = lastName;
				ViewBag.Email = email;
				ViewBag.Phone = phone;
				ViewBag.OfferAmount = offerAmount;
				ViewBag.MoveInDate = moveInDate;
				ViewBag.ClientAddress = clientAddress;
				ViewBag.ClientCity = clientCity;
				ViewBag.ClientZip = clientZip;
				return View("MakeOffer");
			}
			else
			{
				string serializedHome = HttpContext.Session.GetString("CurrentHome");
				Home home = JsonConvert.DeserializeObject<Home>(serializedHome);
				States stateEnum = Enum.Parse<States>(clientState);
				Address newAddress = new Address(clientAddress, clientCity, stateEnum, clientZip);
				Client newClient = new Client(firstName, lastName, newAddress, phone, email);
				int clientID = WriteClient.CreateNew(newClient);
				Client actualClient = ReadClients.GetClientByLastNameAndAddress(newClient);
				Offer newOffer = new Offer(home, actualClient, int.Parse(offerAmount), Enum.Parse<TypeOfSale>(saleType), bool.Parse(sellHome), DateTime.Parse(moveInDate), OfferStatus.Pending);

				int offerID = WriteOffer.CreateNew(newOffer);
				Offer actualOffer = ReadOffers.GetOfferByHomeClientAmount(home, actualClient, int.Parse(offerAmount));

				string seralizedContingencies = HttpContext.Session.GetString("OfferContingencies");
				List<string> currentContingencies = JsonConvert.DeserializeObject<List<string>>(seralizedContingencies);

				Contingencies newContingencies = new Contingencies();
				foreach (string contingency in currentContingencies)
				{
					newContingencies.Add(new Contingency(actualOffer.OfferID, contingency));
				}
				WriteContingencies.CreateNew(newContingencies);




				List<string> confirmationMessage = new List<string>();
				confirmationMessage.Add("Congraulations! Your offer was sucessfully placed!");
				confirmationMessage.Add("Offer First Name: " + actualOffer.Client.FirstName);
				confirmationMessage.Add("Offer Last Name: " + actualOffer.Client.LastName);
				confirmationMessage.Add("Offer Home Address: " + actualOffer.Home.Address.ToString());
				confirmationMessage.Add("Offer Amount: " + actualOffer.Amount);
				TempData["Message"] = JsonConvert.SerializeObject(confirmationMessage);
				TempData["Action"] = "Dashboard";
				TempData["Controller"] = "Dashboard";

				HttpContext.Session.Remove("OfferContingencies");
				HttpContext.Session.Remove("CurrentHome");

				return RedirectToAction("SharedConfirmation", "Shared");
			}


		}

		private bool ValidateOffer(List<string> inputs)
		{
			bool isValid = true;
			if (string.IsNullOrEmpty(inputs[0]))
			{
				isValid = false;
				ViewBag.FnameError = "First Name Is Requried!";
			}
			if (string.IsNullOrEmpty(inputs[1]))
			{
				isValid = false;
				ViewBag.LnameError = "Last Name Is Requried!";
			}
			if (string.IsNullOrEmpty(inputs[2]))
			{
				isValid = false;
				ViewBag.EmailError = "Email Is Requried!";
			}
			if (string.IsNullOrEmpty(inputs[3]))
			{
				isValid = false;
				ViewBag.PhoneError = "Phone Number Is Requried!";
			}
			if (string.IsNullOrEmpty(inputs[4]) || int.TryParse(inputs[4], out _) == false)
			{
				isValid = false;
				ViewBag.AmountError = "Offer Amount Is Requried!";
			}
			if (string.IsNullOrEmpty(inputs[5]))
			{
				isValid = false;
				ViewBag.HomeError = "Current Home Sale Is Requried!";
			}
			if (string.IsNullOrEmpty(inputs[6]) || DateTime.TryParse(inputs[6], out _) == false)
			{
				isValid = false;
				ViewBag.DateError = "Move In Date Is Requried!";
			}
			if (string.IsNullOrEmpty(inputs[7]))
			{
				isValid = false;
				ViewBag.StreetError = "Street Address Sale Is Requried!";
			}
			if (string.IsNullOrEmpty(inputs[8]))
			{
				isValid = false;
				ViewBag.CityError = "City Is Requried!";
			}
			if (string.IsNullOrEmpty(inputs[9]))
			{
				isValid = false;
				ViewBag.ZipError = "Zip CodeIs Requried!";
			}


			return isValid;
		}
		public async Task<IActionResult> Confirmation()
		{
			return View("Confirmation");

		}

		public IActionResult AcceptOffer(int offerID)
		{
			WriteOffer.UpdateOfferStatus(offerID, OfferStatus.Accepted);
			string agentSession = HttpContext.Session.GetString("Agent");
			Agent currentAgent = JsonConvert.DeserializeObject<Agent>(agentSession);
			ViewBag.Agent = currentAgent;

			Offer currentOffer = ReadOffers.GetOfferByOfferID(offerID);


			EmailInfo info = new EmailInfo(
				currentOffer.Client.Email,
				"tur31103@temple.edu",
				"Offer Accepted!",

Project4/Views/Offer/AllOffers.cshtml
@using Newtonsoft.Json
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_AgentLayout.cshtml";
	Offers allOffers = ReadOffers.ReadAllOffers();
	Offers agentOffers = null;
	Agent currentAgent = null;
	string apiUrl = "https://cis-iis2.temple.edu/Fall2024/CIS3342_tui78495/WebAPI/ReadHome/ReadHomeListings";
	HttpClient client = new HttpClient();
	HttpResponseMessage response = client.GetAsync(apiUrl).Result;
	string jsonString = response.Content.ReadAsStringAsync().Result;
	Homes allHomes = JsonConvert.DeserializeObject<Homes>(jsonString);
	if (ViewBag.Agent != null)
	{
		currentAgent = ViewBag.Agent;
		agentOffers = new Offers();
		foreach (Home currentHome in allHomes.List)
		{
			foreach (Offer currentOffer in allOffers.List)
			{
				if (currentHome.AgentID == currentAgent.AgentID)
				{
					if (currentHome.HomeID == currentOffer.Home.HomeID)
					{
						if (currentOffer.Status == OfferStatus.Pending)
						{
							agentOffers.Add(currentOffer);
						}

					}
				}
			}
		}
	}
}
<div class="container">
    <div class="row p-4 shadow mt-5 mb-5">
        <div class="card-header bg-primary text-white d-flex justify-content-between">
            <h2 class="mb-0">Your pending offers</h2>
            <a asp-controller="AgentDashboard" asp-action="AgentDashboard" class="btn btn-secondary">Return To Dashboard</a>
        </div>
        @foreach (Offer currentOffer in agentOffers.List)
        {
            <div class="col-md-4 mt-4 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">@currentOffer.Home.Address.ToString()</h5>
                        <p class="card-text">
                            <strong>Client Name: @currentOffer.Client.FirstName @currentOffer.Client.LastName</strong> <br />
                            <strong>Client Email: @currentOffer.Client.Email</strong> <br />
                            <strong>Asking Price For Home: @currentOffer.Home.Cost</strong> <br />
                            <strong>Offer Amount: @currentOffer.Amount</strong> <br />
                            <strong>Move In Date: @currentOffer.MoveInDate.Date</strong><br />
                            <strong>Offer Contingencies:</strong> <br />
                            <ul>
                                @if (ReadContingencies.GetContingenciesByOfferID(currentOffer.OfferID).List.Count == 0)
                                {
                                    <p>No Contingencies With Offer</p>
                                }
                                else
                                {
                                    @foreach (Contingency currentContingency in ReadContingencies.GetContingenciesByOfferID(currentOffer.OfferID).List)
                                    {
                                        <li>@currentContingency.OfferContingency</li>
                                    }
                                }
     
                            </ul>
                        </p>
                        <div class="d-flex gap-2">
                            <form method="POST" asp-controller="Offer" asp-action="AcceptOffer" asp-route-offerID="@currentOffer.OfferID">
                                <button type="submit" class="btn btn-primary btn-sm me-2" name="AcceptOffer" id="btnViewDetails">Accept Offer</button>
                            </form>
                            <form method="POST" asp-controller="Offer" asp-action="DenyOffer" asp-route-offerID="@currentOffer.OfferID">
                                <button type="submit" class="btn btn-primary btn-sm me-2" name="DenyOffer" id="btnRequestShowing">Deny Offer</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Project4/Views/Offer/MakeOffer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Submit Offer";
}

<div class="container my-4">
    <form asp-controller="Offer" asp-action="FinalizeOffer" method="POST" class="card shadow mt-5 p-3">
        <h4 class="card-title">Make Offer</h4>
        <p class="text-danger">@ViewBag.OfferError</p>
        <div class="row mb-3">
            <div class="col-md-6">
                <label for="txtOfferFirstName" class="form-label">First Name</label>
                <input type="text" id="txtOfferFirstName" name="FirstName" class="form-control" value="@ViewBag.FirstName"/>
                <span class="text-danger">@ViewBag.FnameError</span>
            </div>
            <div class="col-md-6">
                <label for="txtOfferLastName" class="form-label">Last Name</label>
                <input type="text" id="txtOfferLastName" name="LastName" class="form-control" value="@ViewBag.LastName" />
                <span class="text-danger">@ViewBag.FnameError</span>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <label for="txtOfferEmail" class="form-label">Email</label>
                <input type="email" id="txtOfferEmail" name="Email" class="form-control" value="@ViewBag.Email" />
                <span class="text-danger">@ViewBag.EmailError</span>
            </div>
            <div class="col-md-6">
                <label for="OfferPhone" class="form-label">Phone Number</label>
                <input type="tel" id="OfferPhone" name="Phone" class="form-control" value="@ViewBag.Phone" />
                <span class="text-danger">@ViewBag.PhoneError</span>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <label for="OfferAddress" class="form-label">Address</label>
                <input type="text" id="OfferAddress" name="clientAddress" class="form-control" value="@ViewBag.ClientAddress" />
                <span class="text-danger">@ViewBag.StreetError</span>
            </div>
            <div class="col-md-6">
                <label for="OfferCity" class="form-label">City</label>
                <input type="text" id="OfferCity" name="clientCity" class="form-control" value="@ViewBag.ClientCity" />
                <span class="text-danger">@ViewBag.CityError</span>
            </div>

            <div class="col-md-6">
                <label for="OfferState" class="form-label">State</label>
                <select id="OfferState" name="clientState" class="form-control">
                    @foreach (States state in Enum.GetValues(typeof(States)))
                    {
                        <option value="@state">@state</option>
                    }
                </select>
            </div>
            <div class="col-md-6">
                <label for="OfferZip" class="form-label">Zip Code</label>
                <input type="text" id="OfferZip" name="clientZip" class="form-control" value="@ViewBag.ClientZip" />
                <span class="text-danger">@ViewBag.ZipError</span>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <label for="OfferAmount" class="form-label">Offer Amount</label>
                <input type="text" id="OfferAmount" name="OfferAmount" class="form-control" value="@ViewBag.Offer" />
                <span class="text-danger">@ViewBag.AmountError</span>
            </div>
            <div class="col-md-6">
                <label for="SaleType" class="form-label">Offer Type</label>
                <select id="SaleType" name="SaleType" class="form-control">
                    @foreach (TypeOfSale saleType in Enum.GetValues(typeof(TypeOfSale)))
                    {
                        <option value="@saleType">@saleType</option>
                    }
                </select>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <label class="form-label">Sell Current Home</label>
                <div class="form-check">
                    <input type="radio" id="SellHomeYes" name="SellHomePrior" value="true" class="form-check-input" />
                    <label for="SellHomeYes" class="form-check-label">Yes</label>
                </div>
                <div class="form-check">
                    <input type="radio" id="SellHomeNo" name="SellHomePrior" value="false" class="form-check-input" />
                    <label for="SellHomeNo" class="form-check-label">No</label>
                </div>
                <span class="text-danger">@ViewBag.HomeError</span>
            </div>

            <div class="col-md-6">
                <label for="OfferMoveInDate" class="form-label">Move-In Date</label>
                <input type="date" id="OfferMoveInDate" name="MoveInDate" class="form-control" value="@ViewBag.MoveInDate" />
                <span class="text-danger">@ViewBag.DateError</span>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12">
                <label for="txtOfferContingency" class="form-label">Offer Contingency</label>
                <input type="text" id="txtOfferContingency" name="newContingency" class="form-control mb-2" />
                <span class="text-danger">@ViewBag.ContingencyError</span>
                <button type="submit" formaction="/Offer/AddContingency" formmethod="POST" class="btn btn-primary mb-3">Add Contingency</button>

                <table class="table mt-3">
                    <thead>
                        <tr>
                            <th>Contingency</th>
                            <th>Remove Contingency</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (ViewBag.OfferContingencies == null || ViewBag.OfferContingencies.Count == 0)
                        {
                            <tr>
                                <td colspan="2">No Contingencies!</td>
                            </tr>
                        }
                        else
                        {
                            foreach (string offerContingency in ViewBag.OfferContingencies)
                            {
                                <tr>
                                    <td>@offerContingency</td>
                                    <td>
                                        
                                            <input type="hidden" name="removedContingency" value="@offerContingency" />
                                            <button type="submit" formaction="/Offer/RemoveContingency" formmethod="POST" class="btn btn-danger">Remove Contingency</button>

                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>

        <div class="d-flex justify-content-end mt-4">
            <button type="submit" class="btn btn-success me-2 w-100">Submit Offer</button>
            <a asp-controller="MortgageCalculator" asp-action="MortgageCalculator" class="btn btn-primary me-2 w-100">Calculate Mortgage</a>
            <a asp-controller="Dashboard" asp-action="Dashboard" class="btn btn-secondary w-100">Cancel Offer</a>
         
        </div>
    </form>
</div>

Project4/Views/Offer/ViewOffer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}