Project4/Controllers/RealEstateHomeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Project4.Models;
using System.Text;
using System.Text.Json;
using System.IO;
using System.Net;
using System;

namespace Project4.Controllers
{
    //Handles Home Create, Modify and search
    public class RealEstateHomeController : Controller
    {
        private readonly IWebHostEnvironment webhostenvironment;

        public RealEstateHomeController(IWebHostEnvironment webHostEnvironment)
        {
            webhostenvironment = webHostEnvironment;
        }
        [HttpGet]
        public IActionResult CreateHome()
        {
            if (HttpContext.Session.GetString("Agent") == null) { return RedirectToAction("Dashboard", "Dashboard"); }
            return View();
        }
        //Button Controller for Home Form
        [HttpPost]
        public IActionResult HomeForm(string button)
        {
            if (HttpContext.Session.GetString("Agent") == null) { return RedirectToAction("Dashboard", "Dashboard"); }
            //Gets the ID number of a button is it has an ID number. These are present in submit buttons dynamically generated
            int buttonNumber = button.Contains('_') ? int.Parse(button.Split('_').Last()) : -1;
            //handles which submit button was clicked
            switch (button.Split('_').First())
            {
                case "AddRoom":
                    AddRoom();
                    break;
                case "DeleteRoom":
                    DeleteRoom(buttonNumber);
                    break;
                case "AddUtility":
                    AddUtility();
                    break;
                case "DeleteUtility":
                    DeleteUtility(buttonNumber);
                    break;
                case "AddAmenity":
                    AddAmenity();
                    break;
                case "DeleteAmenity":
                    DeleteAmenity(buttonNumber);
                    break;
                case "AddImage":
                    AddImage();
                    break;
                case "DeleteImage":
                    DeleteImage(buttonNumber);
                    break;
                case "UploadImage":
                    UploadImage(buttonNumber);
                    break;
                case "AddHome":
                    Home home = GetHomeData();
                    AddHome(home);
                    break;

            }
            return View("CreateHome");
        }
        //The following functions will add a div dynamically in the razor view 
        //or set a bool value that dictates if a div will be shown or hidden "deleted"
        public void AddRoom()
        {
            if (TempData["RoomCount"] == null)
            {
                TempData["RoomCount"] = 0;
            }
            TempData["RoomCount"] = (int)TempData["RoomCount"] + 1;
            RetainData();
        }
        public void DeleteRoom(int i)
        {
            TempData[$"RoomHidden_{i}"] = true;
            RetainData();
        }
        public void AddUtility()
        {
            if (TempData["UtilityCount"] == null)
            {
                TempData["UtilityCount"] = 0;
            }
            TempData["UtilityCount"] = (int)TempData["UtilityCount"] + 1;
            RetainData();
        }
        public void DeleteUtility(int i)
        {
            TempData[$"UtilityHidden_{i}"] = true;
            RetainData();
        }
        public void AddAmenity()
        {
            if (TempData["AmenityCount"] == null)
            {
                TempData["AmenityCount"] = 0;
            }
            TempData["AmenityCount"] = (int)TempData["AmenityCount"] + 1;
            RetainData();
        }
        public void DeleteAmenity(int i)
        {
            TempData[$"AmenityHidden_{i}"] = true;
            RetainData();
        }
        public void AddImage()
        {
            if (TempData["ImageCount"] == null)
            {
                TempData["ImageCount"] = 0;
            }
            TempData["ImageCount"] = (int)TempData["ImageCount"] + 1;
            RetainData();
        }
        public void DeleteImage(int i)
        {
            TempData[$"ImageHidden_{i}"] = true;
            RetainData();
        }
        //Uploads image to the server
        public void UploadImage(int i)
        {
            TempData["UploadError"] = "";
            IFormFile file = Request.Form.Files[$"fuImage_{i}"];
            if (file == null || file.FileName.Split('.').Last() != "png")
            {
                TempData["UploadError"] = "Image must be a .png!";
                return;
            }
            string agentJson = HttpContext.Session.GetString("Agent");
            Agent agent = System.Text.Json.JsonSerializer.Deserialize<Agent>(agentJson);

            //TODO: Modify Image Learning Opportunity
            //-------------------------------------------------------
            ModifyImage modifyImage = new ModifyImage();
            using (MemoryStream memoryStream = new MemoryStream())
            {
                file.CopyTo(memoryStream);
                modifyImage.Image = memoryStream.ToArray();
            }
            modifyImage.Resize();
            modifyImage.Compress();
            modifyImage.AddWatermark(agent.WorkCompany.CompanyName);
            //-------------------------------------------------------

            //Generate File Name
            string imageName = DateTime.Now.Ticks.ToString() + ".png";

            //I DO NOT HAVE WRITE PERMISSION TO THE SERVER FILE STORAGE 
            //-------------------------------------------------------
            //get the server path 
            //string serverPath = webhostenvironment.ContentRootPath;
            //string path = Path.Combine(serverPath, "..", "Project3", "FileStorage");

            //Upload or display error when uploading image to server
            //try
            //{
            //    using (FileStream fileStream = new FileStream(path, FileMode.CreateNew))
            //    {
            //        fileStream.Write(modifyImage.Image, 0, modifyImage.Image.Length);
            //    }
            //   TempData[$"ImageURL_{i}"] = path;
            //}
            //catch (Exception ex)
            //{
            //    TempData["Errors"] = $"An error occurred while uploading the image. Path: {path} Image Name: {imageName} Error: {ex}";
            //    return;
            //}
            //-------------------------------------------------------
            //To remove the upload button from that specific image on the razor view

            //TODO: Upload File To Local Machine
            string relativePath = $"FileStorage"; // Relative path to the file
            string absolutePath = Path.Combine(Directory.GetCurrentDirectory(), relativePath); // Absolute path to the file
            string fullPath = Path.Combine(absolutePath, imageName);
            Console.WriteLine(fullPath);
            try
            {
                using (FileStream fileStream = new FileStream(fullPath, FileMode.CreateNew))
                {
                    fileStream.Write(modifyImage.Image, 0, modifyImage.Image.Length);
                }
                TempData[$"ImageURL_{i}"] = imageName;
            }
            catch (Exception ex)
            {
                //TODO: add to errors 
                //$"An error occurred while uploading the image. Path: {fullPath} Image Name: {imageName} Error: {ex}";
                return;
            }
            TempData[$"ImageUploaded_{i}"] = true;
            RetainData();
        }
        //Code To Add Home to server through API
        public void AddHome(Home home)
        {
            if (home == null)
            {
                Console.WriteLine("Home was null, failed validation");
                TempData["Response"] = "Invalid home data";
                return;
            }
            //Serialize home to content json 
            StringContent content = new StringContent(
                System.Text.Json.JsonSerializer.Serialize(home),
                Encoding.UTF8,
                "application/json"
            );

            using (HttpClient httpClient = new HttpClient())
            {
                try
                {
                    // Post Request to api sending info through body 
                    HttpResponseMessage response = httpClient.PostAsync(
                        "https://cis-iis2.temple.edu/Fall2024/CIS3342_tui78495/WebAPI/CreateHome/CreateHomeListing",
                        content
                    ).GetAwaiter().GetResult();

                    // Read Response
                    string responseBody = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                    Console.WriteLine($"Response Body: {responseBody}");

                    // Error handling
                    if (responseBody == "-1")
                    {
                        // Home already exists
                        TempData["Response"] = "Error, a home with this address already exists";
                    }
                    else
                    {
                        TempData["Response"] = "Home Created";
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Exception: {ex.Message}");
                    TempData["Response"] = "Web API Connection Error";
                }
            }
        }
        //Get Home Data
        public Home GetHomeData()
        {
            RetainData();

            List<string> validationErrors = new List<string>();
            bool isValidHome = true;
            if (string.IsNullOrWhiteSpace(Request.Form["txtHomeStreet"]))
            {
                validationErrors.Add("Street address is required.");
                isValidHome = false;
            }
            if (string.IsNullOrWhiteSpace(Request.Form["txtHomeCity"]))
            {

Project4/Views/RealEstateHome/AllEditHomes.cshtml
@using Newtonsoft.Json
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_AgentLayout.cshtml";
    Agent currentAgent = null;
    Homes agentHomes = null;

    if (ViewBag.Agent != null)
    {
        currentAgent = ViewBag.Agent;
        agentHomes = ViewBag.AgentHomes;
    }
}
<div class="container">
    <div class="row p-4 shadow mt-5 mb-5">
        <div class="card-header bg-primary text-white d-flex justify-content-between">
            <h2 class="mb-0">Your Home Listings</h2>
            <a asp-controller="AgentDashboard" asp-action="AgentDashboard" class="btn btn-secondary">Return To Dashboard</a>
        </div>
        @foreach (Home currentHome in agentHomes.List)
        {
            <div class="col-md-4 mt-4 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">@currentHome.Address.ToString()</h5>
                        <p class="card-text">
                            <strong>Home Status: @currentHome.SaleStatus</strong> <br />
                            <strong>Home Cost: @currentHome.Cost</strong> <br />
                            <strong>Home Bedrooms: @currentHome.Rooms.GetBedrooms()</strong> <br />
                            <strong>Home Full Bathrooms: @currentHome.Rooms.GetFullBaths()</strong> <br />
                            <strong>Home Half Bathrooms: @currentHome.Rooms.GetHalfBaths()</strong><br />
                            <strong>Date Listed: @currentHome.DateListed</strong> <br />
                        </p>
                        <div class="d-flex gap-2">
                            <a asp-controller="RealEstateHome" asp-action="BackupEditHome" asp-route-homeID="@currentHome.HomeID" class="btn btn-primary btn-sm me-2"> Edit Home Listing</a>
                            @*
                            <form method="POST" asp-controller="RealEstateHome" asp-action="EditHome" asp-route-homeID="@currentHome.HomeID">
                                <button type="submit" class="btn btn-primary btn-sm me-2" name="AcceptOffer" id="btnViewDetails">Edit Home Listing</button>
                            </form>
                            *@
                            <form method="POST" asp-controller="RealEstateHome" asp-action="DeleteHome" asp-route-homeID="@currentHome.HomeID">

                                <button type="submit" class="btn btn-danger btn-sm me-2" name="DenyOffer" id="btnRequestShowing">Delete Home Listing</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Project4/Views/RealEstateHome/CreateHome.cshtml
@*
    You must be a logged in agent to access this page.
*@

@{
	ViewData["Title"] = "Project 4 - Schedule Showing";
	Layout = "~/Views/Shared/_AgentLayout.cshtml";
}
<div class="container my-4">
		<form asp-controller="RealEstateHome" enctype="multipart/form-data" asp-action="HomeForm" method="POST" class="card shadow mt-5 p-3">
		<h1>Create a Home Listing</h1>
		<div class="row mt-3">
			<h2>Home Address</h2>
			<span class="form-label">Street</span>
			<input class="form-control" name="txtHomeStreet" type="text" placeholder="Enter Street" value="@TempData["txtHomeStreet"]">
			<span class="form-label">City</span>
			<input class="form-control" name="txtHomeCity" type="text" placeholder="Enter City" value="@TempData["txtHomeCity"]">
			<span class="form-label">State</span>
			<select class="form-control" name="ddlHomeState" type="text">
				@foreach (States state in Enum.GetValues(typeof(States)))
				{
					if (TempData["ddlHomeState"] != null && TempData["ddlHomeState"].ToString() == state.ToString())
					{
						<option value="@state" selected="selected">@state</option>
					}
					else
					{
						<option value="@state">@state</option>
					}
				}
			</select>
			<span class="form-label">Zip Code</span>
			<input class="form-control" name="txtHomeZipCode" type="text" placeholder="Enter Zip Code" value="@TempData["txtHomeZipCode"]">

		</div>

		<div class="row mt-3">
			<h2>Home Information</h2>
			<span class="form-label">Asking Price</span>
			<input class="form-control" name="txtHomeCost" type="text" placeholder="Enter Asking Price" value="@TempData["txtHomeCost"]">
			<span class="form-label" id="lblPropertyType">Property Type</span>
			<select class="form-control" name="ddlPropertyType">
				@foreach (PropertyType propertyType in Enum.GetValues(typeof(PropertyType)))
				{
					if (TempData["ddlPropertyType"] != null && TempData["ddlPropertyType"].ToString() == propertyType.ToString())
					{
						<option value="@propertyType" selected="selected">@propertyType</option>
					}
					else
					{
						<option value="@propertyType">@propertyType</option>
					}
				}
			</select>
			<span class="form-label">Year Constructed</span>
			<input class="form-control" name="txtYearConstructed" type="text" placeholder="Enter Year Constructed" value="@TempData["txtYearConstructed"]">
			<span class="form-label">Garage Type</span>
			<select class="form-control" name="ddlGarageType">
				@foreach (GarageType garageType in Enum.GetValues(typeof(GarageType)))
				{
					if (TempData["ddlGarageType"] != null && TempData["ddlGarageType"].ToString() == garageType.ToString())
					{
						<option value="@garageType" selected="selected">@garageType</option>
					}
					else
					{
						<option value="@garageType">@garageType</option>
					}
				}
			</select>
			<span class="form-label">Home Description</span>
			<textarea class="form-control" name="txtHomeDescription" rows="4" cols="20" placeholder="Home Description">@TempData["txtHomeDescription"]</textarea>
			<span class="form-label">SaleStatus</span>
			<select class="form-control" name="ddlSaleStatus">
				@foreach (SaleStatus saleStatus in Enum.GetValues(typeof(SaleStatus)))
				{
					if (TempData["ddlSaleStatus"] != null && TempData["ddlSaleStatus"].ToString() == saleStatus.ToString())
					{
						<option value="@saleStatus" selected="selected">@saleStatus</option>
					}
					else
					{
						<option value="@saleStatus">@saleStatus</option>
					}
				}
			</select>
		</div>

		<div class="row mt-3">
			<h2>Add Temperature Control Information</h2>
			<span class="form-label">Cooling</span>
			<select class="form-control" name="ddlCooling">
				@foreach (CoolingTypes coolingType in Enum.GetValues(typeof(CoolingTypes)))
				{
					if (TempData["ddlCooling"] != null && TempData["ddlCooling"].ToString() == coolingType.ToString())
					{
						<option value="@coolingType" selected="selected">@coolingType</option>
					}
					else
					{
						<option value="@coolingType">@coolingType</option>
					}
				}
			</select>
			<span class="form-label">Heating</span>
			<select class="form-control" name="ddlHeating">
				@foreach (HeatingTypes heatingType in Enum.GetValues(typeof(HeatingTypes)))
				{
					if (TempData["ddlHeating"] != null && TempData["ddlHeating"].ToString() == heatingType.ToString())
					{
						<option value="@heatingType" selected="selected">@heatingType</option>
					}
					else
					{
						<option value="@heatingType">@heatingType</option>
					}
				}
			</select>
		</div>

		<div class="row mt-3">
			<h2>Add Room Information</h2>
			@if (TempData["RoomCount"] == null)
			{
				TempData["RoomCount"] = 0;
			}
			@for (int i = 0; i < (int)TempData["RoomCount"]; i++)
			{
				if (TempData[$"RoomHidden_{i}"] == null)
				{
					TempData[$"RoomHidden_{i}"] = false;
				}
				<div @((bool)TempData[$"RoomHidden_{i}"] ? "hidden" : "")>
					<div class="row align-items-center mt-2">
						<div class="col-md-3">
							<span class="form-label">Length: </span>
							<input class="form-control col-md-2" name="txtLength_@i" type="text" placeholder="Enter Length" value="@TempData[$"txtLength_{i}"]">
						</div>
						<div class="col-md-3">
							<span class="form-label">Width: </span>
							<input class="form-control" name="txtWidth_@i" type="text" placeholder="Enter Width" value="@TempData[$"txtWidth_{i}"]">
						</div>
						<div class="col-md-3">
							<span class="form-label">RoomType: </span>
							<select class="form-control" name="ddlRoomType_@i">
								@foreach (RoomType roomType in Enum.GetValues(typeof(RoomType)))
								{
									if (TempData[$"ddlRoomType_{i}"] != null && TempData[$"ddlRoomType_{i}"].ToString() == roomType.ToString())
									{
										<option value="@roomType" selected="selected">@roomType</option>
									}
									else
									{
										<option value="@roomType">@roomType</option>
									}
								}
							</select>
						</div>

						<div class="col-md-3 mt-4">
							<button class="btn btn-danger w-100" type="submit" name="button" value="DeleteRoom_@i">Delete Room</button>
						</div>


					</div>
				</div>
			}
			<button class="btn btn-primary mt-3" type="submit" name="button" value="AddRoom">Add Room</button>
		</div>

		<div class="row mt-3">
			<h2>Add Utility Information</h2>
			@if (TempData["UtilityCount"] == null)
			{
				TempData["UtilityCount"] = 0;
			}
			@for (int i = 0; i < (int)TempData["UtilityCount"]; i++)
			{
				if (TempData[$"UtilityHidden_{i}"] == null)
				{
					TempData[$"UtilityHidden_{i}"] = false;
				}
				<div @((bool)TempData[$"UtilityHidden_{i}"] ? "hidden" : "")>
					<div class="row align-items-center mt-2">
						<div class="col-md-5">
							<span class="form-label">Utility Information: </span>
							<input class="form-control" name="txtUtilityInformation_@i" type="text" placeholder="Enter Utility Information" value="@TempData[$"txtUtilityInformation_{i}"]">
						</div>
						<div class="col-md-5">
							<span class="form-label">Utility Type: </span>
							<select class="form-control" name="ddlUtilityType_@i">
								@foreach (UtilityTypes utilityType in Enum.GetValues(typeof(UtilityTypes)))
								{
									if (TempData[$"ddlUtilityType_{i}"] != null && TempData[$"ddlUtilityType_{i}"].ToString() == utilityType.ToString())
									{
										<option value="@utilityType" selected="selected">@utilityType</option>
									}
									else
									{
										<option value="@utilityType">@utilityType</option>
									}
								}
							</select>
						</div>
						<div class="col-md-2 mt-4">
							<button class="btn btn-danger w-100" type="submit" name="button" value="DeleteUtility_@i">Delete Utility</button>
						</div>
					</div>
				</div>
			}
			<button class="btn btn-primary mt-3" type="submit" name="button" value="AddUtility">Add Utility</button>
		</div>

		<div class="row mt-3">
			<h2>Add Amenity Information</h2>
			@if (TempData["AmenityCount"] == null)
			{
				TempData["AmenityCount"] = 0;
			}
			@for (int i = 0; i < (int)TempData["AmenityCount"]; i++)
			{
				if (TempData[$"AmenityHidden_{i}"] == null)
				{
					TempData[$"AmenityHidden_{i}"] = false;
				}
				<div @((bool)TempData[$"AmenityHidden_{i}"] ? "hidden" : "")>
					<div class="row align-items-center mt-2">
						<div class="col-md-5">
							<span class="form-label">Amenity Information: </span>
							<input class="form-control" name="txtAmenityInformation_@i" type="text" placeholder="Enter Amenity Information" value="@TempData[$"txtAmenityInformation_{i}"]">
						</div>
						<div class="col-md-5">
							<span class="form-label">Amenity Type: </span>
							<select class="form-control" name="ddlAmenityType_@i">
								@foreach (AmenityType amenityType in Enum.GetValues(typeof(AmenityType)))
								{
									if (TempData[$"ddlAmenityType_{i}"] != null && TempData[$"ddlAmenityType_{i}"].ToString() == amenityType.ToString())
									{
										<option value="@amenityType" selected="selected">@amenityType</option>
									}
									else
									{
										<option value="@amenityType">@amenityType</option>
									}
								}
							</select>
						</div>
						<div class="col-md-2 mt-4">
							<button class="btn btn-danger w-100" type="submit" name="button" value="DeleteAmenity_@i">Delete Amenity</button>
						</div>
					</div>
				</div>
			}
			<button class="btn btn-primary mt-3" type="submit" name="button" value="AddAmenity">Add Amenity</button>
		</div>

		<div class="row mt-3">
			<h2>Add Image Information</h2>
			<p class="text-danger">@TempData["UploadError"]</p>
			@if (TempData["ImageCount"] == null)
			{
				TempData["ImageCount"] = 0;
			}
			@for (int i = 0; i < (int)TempData["ImageCount"]; i++)
			{
				if (TempData[$"ImageHidden_{i}"] == null)
				{
					TempData[$"ImageHidden_{i}"] = false;
				}
				if (TempData[$"ImageUploaded_{i}"] == null)
				{
					TempData[$"ImageUploaded_{i}"] = false;
				}
				<div @((bool)TempData[$"ImageHidden_{i}"] ? "hidden" : "")>
					<div class="row align-items-center mt-2">
						<div class="col-md-3">
							<span class="form-label">Image Information: </span>
							<input class="form-control" name="txtImageInformation_@i" type="text" placeholder="Enter Image Information" value="@TempData[$"txtImageInformation_{i}"]">
						</div>
						<div class="col-md-2">
							<span class="form-label">Image Type: </span>
							<select class="form-control" name="ddlImageRoomType_@i">
								@foreach (RoomType roomType in Enum.GetValues(typeof(RoomType)))
								{
									if (TempData[$"ddlImageRoomType_{i}"] != null && TempData[$"ddlImageRoomType_{i}"].ToString() == roomType.ToString())
									{
										<option value="@roomType" selected="selected">@roomType</option>
									}
									else
									{
										<option value="@roomType">@roomType</option>
									}
								}
							</select>
						</div>
						@if ((bool)TempData[$"ImageUploaded_{i}"])
						{
							<span class="form-label fw-bold">Image Uploaded To Server.</span>
						}
						else
						{
							<div class="col-md-3">
								<input class="form-control mt-4" type="file" name="fuImage_@i">
							</div>
							<div class="col-md-2">
								<button class="btn btn-info w-100 mt-4" type="submit" name="button" value="UploadImage_@i">Upload Image</button>
							</div>
						}
						@if (i != 0)
						{
							<div class="col-md-2">
								<button class="btn btn-danger w-100 mt-4" type="submit" name="button" value="DeleteImage_@i">Delete Image</button>
							</div>
						}
					</div>
				</div>
			}
			<button class="btn btn-primary mt-3" type="submit" name="button" value="AddImage">Add Image</button>
		</div>
		<div class="row">

			<div class="col-12 mt-3">
				<button class="btn btn-success w-100" type="submit" name="button" value="AddHome">Submit Home</button>
			</div>
		</div>

        @if(TempData["Response"] != null)
        {
            <p class="text-danger">@TempData["Response"]</p>
        }

		@if (TempData["ValidationError"] != null)
		{
			List<string> validationErrors = TempData["ValidationError"] as List<string>;

			<ul>
				@foreach (string error in validationErrors)
				{
					<li class="text-danger">@error</li>
				}
			</ul>
		}
	</form>
</div>

Project4/Views/RealEstateHome/ViewAllHomes.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}